services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: springauth
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always